# docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: ./backend # Path to your backend directory
    restart: unless-stopped
    env_file: ./backend/.env # Load environment variables from a .env file
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend # Path to your frontend directory
    restart: unless-stopped
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: